# Generated by Django 5.0.1 on 2024-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=100),
            preserve_default=False,
        ),
    ]
